### ISSUE TITLE
ECSIS 2022 - Revisões e comentários

### ISSUE THREAD

**Issue by rodrigofolha** [rodrigofolha/foodchain#14]
**Plataformas**: temos que revisar a literatura relacionada com plataformas digitais.

- [ ] The paper takes the context of Brazil’s food delivery platforms, perhaps it would have been better to explain the context in terms of platform and data regulations, compliance, gig worker conditions, gig worker wages.

**Entrevistas**: muito do que o revisor 3 fala é um pouco achismo  ("deveria ser de um modo ou de outro''). Isso pode ser eliminado com entrevistas com stakeholders. Se os stakeholders concordam com a solução, então o que nós ou revisores achamos fica secundário.  

- [ ] While identifying and grounding the design requirements in interviews with restaurant owners and customers is a wise choice for motivating for the problem and justifying the solution, it is not clear why or why not delivery workers aren’t interviewed for incorporating their perspective in the design. Providing reasons for why they are excluded, and considering implications of excluding them, would strengthen the justification of methodological choices.

- [ ] Evaluation. In the evaluation step of the DSR, different methods for evaluation are adopted for different design requirements. While these appear relevant, it could serve from being complemented by pointing out that the solution is not yet evaluated in use (as I understand is advocated for in the DSR framework that is adopted by Peffers et al. (2007)) and describing potential implications/limitations of that. For example, I am pondering whether such evaluation would render useful insights for the user interface design of the  DApps. There appears to be several active steps for stakeholders (e.g. encrypting private data, acknowledging correct items) when interacting with the DApp, and evaluation in use may reveal significant feedback for designing the interface of DApps for removing eventual barriers of use. I note that you propose ex-post interviews with stakeholders that could provide feedback for a second design cycle in the conclusion but as this is not research-in-progress, the paper should as well be written as completed research. Including a note on limitations could be  one way to adapt the paper, that still includes the thoughts on ex-post interviews.

- [ ] The proposed architecture adds a lot of new steps for the consumers, the delivery workers and restaurants. It lacks clarity as to which of them would run in the background and which of them require the user to actively engage when it comes to  permissions, sharing data, public keys, etc. A little more clarity on that is much appreciated, the key to better adoption be in reducing the number of steps it would take for each actor in a transaction.

- [ ] Unlike social media platforms, which rely on individual patterns for targetted advertisements, the delivery apps rely on aggregate metrics for consumer patterns in a specific region, location metrics of restaurants, etc. to support new and small-scale restaurants through consultation. The tools allow for better matching of consumers with the businesses through analytics and projections. This helps in the customer retention of both, the consumers and the restaurants on the platform in the long run. What would be some features of a community-based blockchain solution that would encourage cross-sided network effects?

- [ ] In page 5, the author(s) mention that restaurants can add constraints regarding delivery, the rationale behind restaurants having control over delivery is not very clear. The nature of the business is to decouple the restaurants and the delivery workers.

- [ ] In page 9, the author(s) suggest a consortium of restaurant associations, consumer protection groups and delivery worker unions. Delivery work on platforms is a form of gig work and usually do not form unions. In which case, it could lead to unfair representation or social groups that take the responsibility to represent the delivery workers. As I understand, a permissioned blockchain would mean the network has to be initiated by a group/company which would pour resources into development, marketing, getting stakeholders and their representatives, training,  etc. When we go from permissionless to permissioned blockchain, the role of a central body/foundation/authority becomes much more prominent. The draft does not shed light into the delegation of tasks and incentives for functional bodies of such an ecosystem.

**Explicações**: os revisores acharam que vários pontos deveriam ser melhor explicados e ilustrados. Por exemplo, screenshots mostrando a interação com a ferramenta. Eu concordo, porém não tínhamos espaço na nossa submissão. Isso pode ser resolvido em uma submissão estendida para jornal.  
Problematization. A strength of the paper is the identification of an important and urgent problem area: the increasingly skewed dependencies between stakeholders such as restaurants, customers and delivery workers on centralized food delivery platforms, and the implications of these dependencies, i.e. imbalances of control over monetary and data flows. Starting the 2nd section of the introduction with a problem statement in one or two sentences may bring the problem even more to the forefront. The current content of the introduction section can be used to motivate the problem and justify the value of a solution to this problem.

- [ ] Design requirements. The paper elaborates three design requirements of an “ideal” food delivery platform which are clearly presented. Design requirement #2 about conflict resolution is particularly clear and well-motivated for. Some ambiguities  remain however that could be addressed in a revision of the paper.

- [ ] Design requirement #1 tackles issues of power imbalance in cost distribution between stakeholders in contexts with centralized platforms, where the design requirement formulation argues that “food delivery services must be supported by systems that ensure economic feasibility”. Here, it is unclear what economic feasibility refers to and for whom it should be considered economically feasible.  It is also possible that different actors in an ecosystem may have different views on what constitutes economic feasibility. Is there a way to define economic feasibility or specify for whom it should be economically feasible to avoid confusion or conflicts regarding what it means? Can another concept than economic feasibility provide more clarity? For example, Oh et al. (2015) discusses this  issue in terms of actors perceiving revenue-sharing models (un)fair in the context of relationships between platform owners and app developers. Revising the formulation and clearly define concepts in the design requirement can help improving conceptual clarity.

- [ ] Design requirement #3 tackles issues of privacy for stakeholders, why it argues that stakeholder data should not be publicly available. While it is an important issue, this design requirement currently lacks grounded justification given that it is not raised in the interviews. Is there another way to justify the principle, for example by not restricting the method for understanding the problem to the interviews? Literature on, for example, surveillance (Zuboff, 2015), law (e.g. GDPR) and/or ethics may help arguing for such design requirement. Further, it is a bit unclear how the paper views the boundary between public and private in the context of the design. An alternative formulation to avoid this ambiguity could be, for example, that “data should be available only for X” (if an unambiguous definition of X can be formulated).

    
- [ ] In centralised systems (as with Wolt and other food delivery systems), there is one clear entity which can be held liable for any kind of data breach. It is not clear from the paper, who holds liability with blockchain system?

- [ ] In centralised systems (as with Wolt and other food delivery systems), delivery staffs have possibility to unionise to negotiate better wages. With Blokchain system, if the multiple restaurants collude among themselves, they hold enough influence to hold the wages for delivery staffs down. How can such collusion be prevented with the proposed system?

- [ ] In the proposed solution (Fig 2), it seems that restaurants have overwhelming authority. One of issues with the smart contract is that the entire process is automated and there is no room of consideration of external factors which may arise. For example, what happens if the staff can not deliver the food on time due to traffic reason? As the manuscript righty pointedout that with food delivery systems being in charge, restaurants have to bear the cost as a major motivation of the work, but with the smart contract in the place, the same could be transferred to delivery staffs!

- [ ] However, the workflow of the proposed system is difficult to follow from figure 2. The paper would be enhanced by explaining the workflow of the figure better.   The choice of permissioned blockchain is very appropriate for the solution to reduce the cost. However, it is not clear which organizational entity would hold the membership permissions for adding/removing members of the blockchain. If the restaurant association holds such authority, then they control the entire system. These aspects should be addressed. Please address the issues mentioned by reviewer 3.

- [ ] In page 5, the author(s) suggest restaurants to put up their own proprietary websites or public databases/domains. This adds to an additional cost, not only the capital involved in maintaining the server, website, domain name but also, human capital for creating and updating the menus and the website. A consolidated platform gives better visibility and discoverability, a systemic approach to data of multiple restaurants removes the need for technical knowledge of the restaurant manager. The case suggested the restaurant would only rely on the consumers who would already know the name of the restaurant with a lot of uncertainty as to if  the website is updated, payment methods, genuineness of the website/restaurant, etc.

**Reestruturação**:

- [ ] Theory. The paper defines blockchain as a distributed, decentralized and append- only database. In my reading, centralization, distribution, and decentralization are core theoretical concepts throughout the paper. While the paper clearly outlines what is meant by distributed, decentralized, append-only and nodes, the organizing implications of these properties in the context of platform-based ecosystems are less clear, as well as how these properties make blockchain-based platforms distinct from centralized platforms. As an example of a paper that addresses such issues, see Vergne (2020). One way to approach this can be to devote section 3.1. to a broader section on digital platforms, with a distinct  focus on what distinguishes centralized from decentralized and distributed  platforms, and outline what implications they have for agency of and relationships  between stakeholders.

- [ ]  Future research. The paper expresses interest in exploring how the design can be generalized to other areas of logistics. While this is indeed an exciting direction, I propose that these ideas are presented in a distinct section on directions for future research. Again, this is not a research-in-progress paper but the paper should be presented as completed research. Thereby, it is out of place to frame the ideas on future research as the authors’ upcoming plans.

- [ ]  Structure. Overall, the paper is well structured through following the steps of the DSR framework. However, the structure is somewhat disrupted in chapter 6. As a suggestion for improvement, consider if you could remove the subheading 6.2.3. Discussion and integrate it in section 6.2 somehow.
